Handle more complex id patterns
hapijs/bassmaster pull request #75
Opened 2016-11-29 15:40 UTC by profpylons

Updated a validation regex to add support for Id's which contain dashes (like uuid's) and dots (like file names).
So id's like `55cf-687663-55cf687663.png` can now be piped from responses to other requests in the batch.

2016-12-15 02:32 UTC, cadecairos requested changes
Great PR, thanks for including tests. I just have one small change request.

2016-12-15 02:32 UTC, cadecairos commented on package.json
> +  "version": "2.0.3",
Lets not bump the version in this commit

2016-12-17 03:35 UTC, cadecairos approved these changes

2016-12-17 04:10 UTC, merged

2016-12-19 09:39 UTC, profpylons commented
Thanks for the merge. 

There are some [more changes](https://github.com/profpylons/bassmaster/tree/loop-array-responses) in the works - you can read the intention in the README, if you wish to comment.